# Auto-generated by .github/workflows/release.yml.
# Hand-edits will be overwritten on the next release.
#
# Source of truth: this file in the InLook repo. The StruisICT/homebrew-tap
# repo mirrors it at Casks/inlook.rb.
cask "inlook" do
  version "0.5.0"
  sha256 "588d5187bc051fa7747318edbf389104513787dd1fb81305f09512599571e59c"

  url "https://github.com/StruisICT/InLook/releases/download/v#{version}/InLook-#{version}-universal.dmg"
  name "InLook"
  desc "Fast, free .eml email viewer"
  homepage "https://github.com/StruisICT/InLook"

  app "InLook.app"

  zap trash: [
    "~/Library/Preferences/nl.struisict.inlook.plist",
    "~/Library/Saved Application State/nl.struisict.inlook.savedState",
  ]
end
