# Auto-generated by .github/workflows/release.yml.
# Hand-edits will be overwritten on the next release.
#
# Source of truth: this file in the InLook repo. The Struis112/homebrew-tap
# repo mirrors it at Casks/inlook.rb.
cask "inlook" do
  version "0.4.0"
  sha256 "b1685014f39ff8cd4f510966b4e4619a85e374eb77d9179a8a2903f066d573ca"

  url "https://github.com/Struis112/InLook/releases/download/v#{version}/InLook-#{version}-universal.dmg"
  name "InLook"
  desc "Fast, free .eml email viewer"
  homepage "https://github.com/Struis112/InLook"

  app "InLook.app"

  zap trash: [
    "~/Library/Preferences/nl.struisict.inlook.plist",
    "~/Library/Saved Application State/nl.struisict.inlook.savedState",
  ]
end
